name: Deploy Feature

on:
  push:
    branches:
      - main
      - feature/*

  workflow_dispatch:

jobs:

  build:
    name: Build Debug Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Generate Dev APK
        run: ./gradlew assembleDebug

      - name: List build output
        if: always()
        run: |
          echo "Build outputs"
          cd ${{ github.workspace }}/app/build/outputs/apk/debug/
          tree -a

      - name: Export build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-build
          path: |
            ${{ github.workspace }}/app/build/outputs/apk/debug/*.apk
          retention-days: 3

  deploy:
    name: Deploy Debug Build
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download All Artifacts
        uses: actions/download-artifact@v4

      - name: Install AppCenter CLI
        run: |
          npm install -g appcenter-cli
          echo "List downloads folder contents:"
          ls -R
        shell: bash

      - name: Upload Debug Build to Appcenter
        run: |
          sh ${{ github.workspace }}/.github/scripts/app_center_release_notes.sh releaseNotes
          cat release_notes_markdown.md
          appcenter distribute groups publish -f ./dev-build/app-debug.apk --token ${{ secrets.APP_CENTER_TOKEN }} --app GithubTest/GitHubActionsSandbox -g "Beta Testers" -R release_notes_markdown.md --debug
        shell: bash